### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by thepwagner**
Ugly build prevents a >300mb container.

### CODE REVIEW

**Comment by DeviaVir** [comment]
@thepwagner this will become a global service running on all nodes to throw journald logs into cloudwatch?

**Comment by thepwagner** [comment]
@DeviaVir I was planning on dropping it via user-data; so not a "global service" in the fleet sense.

I think user-data is the easiest way to pass the `LOG_GROUP` variable value, so defining the whole service in user-data felt nicer than dropping an .env file and coupling with a fleet "global service" (even if the latter is easier to stop/upgrade etc).

**Comment by DeviaVir** [comment]
@thepwagner I'm a bit conflicted, as we already have cloudwatch logs using the global service method- why does it make more sense for you to use the user-data method?

**Comment by DeviaVir** [comment]
@thepwagner +1 on user-data; we want to be able to specify per service if we want to do logging to cloudwatch, not globally on all

**Pull request merged**
